class Bank {
  static String name;
  static String branch;
  static String location;
  static String ifscCode;
  static String managerName;
  static int employeesCount;
  static int customersCount;
  static double totalAssets;
  static double interestRate;
  static boolean isInternational;
  static String bankCode;
  static boolean onlineBankingAvailable;
  static String establishedDate;
  static String licenseNumber;
  static String currencyType;
  static String contactNumber;
  static boolean hasATM;
  static boolean isPrivate;
  static boolean isGovernment;
  static String timings;

  public static void main(String[] ar) {
    System.out.println("--------Default Values--------");
    System.out.println("Bank Name: " + name);
    System.out.println("Branch: " + branch);
    System.out.println("Location: " + location);
    System.out.println("IFSC: " + ifscCode);
    System.out.println("Manager: " + managerName);
    System.out.println("Employees: " + employeesCount);
    System.out.println("Customers: " + customersCount);
    System.out.println("Assets: " + totalAssets);
    System.out.println("Interest Rate: " + interestRate + "%");
    System.out.println("International: " + isInternational);
    System.out.println("Bank Code: " + bankCode);
    System.out.println("Online Banking: " + onlineBankingAvailable);
    System.out.println("Established: " + establishedDate);
    System.out.println("License: " + licenseNumber);
    System.out.println("Currency: " + currencyType);
    System.out.println("Timings" + timings);
    System.out.println("It Is Government :" + isGovernment);
    System.out.println("It Has ATM:" + hasATM);
    System.out.println("Contact Number:" + contactNumber);
    System.out.println("IS Private :" + isPrivate);
    System.out.println("--------Actual Values--------");
    
    name = "State Bank";
    branch = "MG Road";
    location = "Bangalore";
    ifscCode = "SBIN0001234";
    managerName = "Rahul Sharma";
    employeesCount = 50;
    customersCount = 5000;
    totalAssets = 12000000.50;
    interestRate = 6.5;
    isInternational = false;
    bankCode = "SB123";
    onlineBankingAvailable = true;
    establishedDate = "01-01-1970";
    licenseNumber = "LIC876543";
    currencyType = "INR";
    contactNumber = "08012345678";
    hasATM = true;
    isPrivate = false;
    isGovernment = true;
    timings = "9 AM to 4 PM";

    System.out.println("Bank Name: " + name);
    System.out.println("Branch: " + branch);
    System.out.println("Location: " + location);
    System.out.println("IFSC: " + ifscCode);
    System.out.println("Manager: " + managerName);
    System.out.println("Employees: " + employeesCount);
    System.out.println("Customers: " + customersCount);
    System.out.println("Assets: " + totalAssets);
    System.out.println("Interest Rate: " + interestRate + "%");
    System.out.println("International: " + isInternational);
    System.out.println("Bank Code: " + bankCode);
    System.out.println("Online Banking: " + onlineBankingAvailable);
    System.out.println("Established: " + establishedDate);
    System.out.println("License: " + licenseNumber);
    System.out.println("Currency: " + currencyType);
    System.out.println("Timings" + timings);
    System.out.println("It Is Government :" + isGovernment);
    System.out.println("It Has ATM:" + hasATM);
    System.out.println("Contact Number:" + contactNumber);
    System.out.println("IS Private :" + isPrivate);
  }
}
