class Court {
    static String name;
    static String type;
    static String location;
    static int judgesCount;
    static int pendingCases;
    static int solvedCases;
    static String chiefJudge;
    static boolean eFilingAvailable;
    static boolean onlineStatusCheck;
    static int staffCount;
    static String workingHours;
    static boolean legalAidAvailable;
    static int courtRooms;
    static boolean hasLibrary;
    static boolean ccTV;
    static String contactEmail;
    static String contactNumber;
    static String jurisdiction;
    static String barAssociationName;
    static boolean mediationAvailable;

    public static void main(String[] ar) {
        System.out.println("--------Default Values--------");
        System.out.println("Court Name: " + name);
        System.out.println("Type: " + type);
        System.out.println("Location: " + location);
        System.out.println("Judges Count: " + judgesCount);
        System.out.println("Pending Cases: " + pendingCases);
        System.out.println("Solved Cases: " + solvedCases);
        System.out.println("Chief Judge: " + chiefJudge);
        System.out.println("E-Filing: " + eFilingAvailable);
        System.out.println("Online Status Check: " + onlineStatusCheck);
        System.out.println("Staff Count: " + staffCount);
        System.out.println("Working Hours: " + workingHours);
        System.out.println("Legal Aid Available: " + legalAidAvailable);
        System.out.println("Court Rooms: " + courtRooms);
        System.out.println("Library Available: " + hasLibrary);
        System.out.println("CCTV Installed: " + ccTV);
        System.out.println("Email: " + contactEmail);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Jurisdiction: " + jurisdiction);
        System.out.println("Bar Association: " + barAssociationName);
        System.out.println("Mediation Available: " + mediationAvailable);
        System.out.println("--------Actual  Values--------");

        name = "High Court of Karnataka";
        type = "High Court";
        location = "Bangalore";
        judgesCount = 75;
        pendingCases = 25000;
        solvedCases = 18000;
        chiefJudge = "Justice Ravi Kumar";
        eFilingAvailable = true;
        onlineStatusCheck = true;
        staffCount = 150;
        workingHours = "10:00 AM - 5:00 PM";
        legalAidAvailable = true;
        courtRooms = 20;
        hasLibrary = true;
        ccTV = true;
        contactEmail = "info@karnatakajudiciary.in";
        contactNumber = "080-12345678";
        jurisdiction = "State of Karnataka";
        barAssociationName = "Karnataka Bar Council";
        mediationAvailable = true;

        System.out.println("Court Name: " + name);
        System.out.println("Type: " + type);
        System.out.println("Location: " + location);
        System.out.println("Judges Count: " + judgesCount);
        System.out.println("Pending Cases: " + pendingCases);
        System.out.println("Solved Cases: " + solvedCases);
        System.out.println("Chief Judge: " + chiefJudge);
        System.out.println("E-Filing: " + eFilingAvailable);
        System.out.println("Online Status Check: " + onlineStatusCheck);
        System.out.println("Staff Count: " + staffCount);
        System.out.println("Working Hours: " + workingHours);
        System.out.println("Legal Aid Available: " + legalAidAvailable);
        System.out.println("Court Rooms: " + courtRooms);
        System.out.println("Library Available: " + hasLibrary);
        System.out.println("CCTV Installed: " + ccTV);
        System.out.println("Email: " + contactEmail);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Jurisdiction: " + jurisdiction);
        System.out.println("Bar Association: " + barAssociationName);
        System.out.println("Mediation Available: " + mediationAvailable);
    }
}
