class Desktop {
  static String brand;
  static String model;
  static String processor;
  static int ramSize;
  static int storageSize;
  static String storageType;
  static String os;
  static String graphicsCard;
  static boolean isWiFiEnabled;
  static int usbPorts;
  static boolean bluetoothAvailable;
  static String motherboard;
  static int powerSupply;
  static String cabinetType;
  static double weight;
  static boolean hasMonitor;
  static int monitorSize;
  static String keyboardType;
  static String mouseType;
  static String color;

  public static void main(String[] ar) {
    brand = "HP";
    System.out.println("--------Default Values--------");
    System.out.println("Desktop: " + brand + ", Processor: " + processor + ", RAM: " + ramSize + "GB");
    System.out.println("Color :" + color);
    System.out.println("Power Supply:" + powerSupply);
    System.out.println("Mouse Tpe:" + mouseType);
    System.out.println("Key Board type :" + keyboardType);
    System.out.println("Monitor Size :" + monitorSize);
    System.out.println("Has Monitor :" + hasMonitor);
    System.out.println("Weight :" + weight);
    System.out.println("Cabinet type:" + cabinetType);
    System.out.println("Mother Board :" + motherboard);
    System.out.println("Blueeth Available :" + bluetoothAvailable);
    System.out.println("USB POrts :" + usbPorts);
    System.out.println("Model :" + model);
    System.out.println("Storage Size :" + storageSize);
    System.out.println("Is WIFI Enable:" + isWiFiEnabled);
    System.out.println("Operating System :" + os);
    System.out.println("Storage Type:" + storageType);
    System.out.println("Graphics Card" + graphicsCard);
    System.out.println("--------Actual Values--------");
    model = "Pavilion 590";
    processor = "Intel i7";
    ramSize = 16;
    storageSize = 1000;
    storageType = "SSD";
    os = "Windows 11";
    graphicsCard = "NVIDIA GTX 1650";
    isWiFiEnabled = true;
    usbPorts = 6;
    bluetoothAvailable = true;
    motherboard = "HP OEM";
    powerSupply = 450;
    cabinetType = "Mid Tower";
    weight = 6.5;
    hasMonitor = true;
    monitorSize = 24;
    keyboardType = "Mechanical";
    mouseType = "Optical";
    color = "Black";

    System.out.println("Desktop: " + brand + ", Processor: " + processor + ", RAM: " + ramSize + "GB");
    System.out.println("Color :" + color);
    System.out.println("Power Supply:" + powerSupply);
    System.out.println("Mouse Tpe:" + mouseType);
    System.out.println("Key Board type :" + keyboardType);
    System.out.println("Monitor Size :" + monitorSize);
    System.out.println("Has Monitor :" + hasMonitor);
    System.out.println("Weight :" + weight);
    System.out.println("Cabinet type:" + cabinetType);
    System.out.println("Mother Board :" + motherboard);
    System.out.println("Blueeth Available :" + bluetoothAvailable);
    System.out.println("USB POrts :" + usbPorts);
    System.out.println("Model :" + model);
    System.out.println("Storage Size :" + storageSize);
    System.out.println("Is WIFI Enable:" + isWiFiEnabled);
    System.out.println("Operating System :" + os);
    System.out.println("Storage Type:" + storageType);
    System.out.println("Graphics Card" + graphicsCard);
  }
}
