class Gym {
    static String name;
    static String location;
    static int membersCount;
    static int trainersCount;
    static boolean hasCardioSection;
    static boolean hasWeightSection;
    static boolean hasSauna;
    static boolean hasSteamRoom;
    static boolean personalTrainingAvailable;
    static boolean dietConsultation;
    static String openingTime;
    static String closingTime;
    static int machinesCount;
    static String ownerName;
    static double membershipFee;
    static boolean acAvailable;
    static String contactNumber;
    static boolean ladiesOnlySection;
    static boolean lockerFacility;
    static boolean musicSystem;

    public static void main(String[] ar) {
        System.out.println("--------Default Valuee-----------");
        System.out.println("Gym Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Members: " + membersCount);
        System.out.println("Trainers: " + trainersCount);
        System.out.println("Cardio: " + hasCardioSection);
        System.out.println("Weight Section: " + hasWeightSection);
        System.out.println("Sauna: " + hasSauna);
        System.out.println("Steam Room: " + hasSteamRoom);
        System.out.println("Personal Training: " + personalTrainingAvailable);
        System.out.println("Diet Consultation: " + dietConsultation);
        System.out.println("Opening Time: " + openingTime);
        System.out.println("Closing Time: " + closingTime);
        System.out.println("Machines: " + machinesCount);
        System.out.println("Owner: " + ownerName);
        System.out.println("Fee: ₹" + membershipFee);
        System.out.println("AC Available: " + acAvailable);
        System.out.println("Contact: " + contactNumber);
        System.out.println("Ladies Only Section: " + ladiesOnlySection);
        System.out.println("Locker Facility: " + lockerFacility);
        System.out.println("Music System: " + musicSystem);
        System.out.println("--------Actual Value------------");
        name = "Gym";
        location = "Hebbala";
        membersCount = 150;
        trainersCount = 5;
        hasCardioSection = true;
        hasWeightSection = true;
        hasSauna = true;
        hasSteamRoom = false;
        personalTrainingAvailable = true;
        dietConsultation = true;
        openingTime = "5:30 AM";
        closingTime = "10:30 PM";
        machinesCount = 35;
        ownerName = "Manoj";
        membershipFee = 1500.00;
        acAvailable = true;
        contactNumber = "9876500000";
        ladiesOnlySection = true;
        lockerFacility = true;
        musicSystem = true;

        System.out.println("Gym Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Members: " + membersCount);
        System.out.println("Trainers: " + trainersCount);
        System.out.println("Cardio: " + hasCardioSection);
        System.out.println("Weight Section: " + hasWeightSection);
        System.out.println("Sauna: " + hasSauna);
        System.out.println("Steam Room: " + hasSteamRoom);
        System.out.println("Personal Training: " + personalTrainingAvailable);
        System.out.println("Diet Consultation: " + dietConsultation);
        System.out.println("Opening Time: " + openingTime);
        System.out.println("Closing Time: " + closingTime);
        System.out.println("Machines: " + machinesCount);
        System.out.println("Owner: " + ownerName);
        System.out.println("Fee: ₹" + membershipFee);
        System.out.println("AC Available: " + acAvailable);
        System.out.println("Contact: " + contactNumber);
        System.out.println("Ladies Only Section: " + ladiesOnlySection);
        System.out.println("Locker Facility: " + lockerFacility);
        System.out.println("Music System: " + musicSystem);
    }

}