public class MarbleRunner {
    public static void main(String[] args) {
        Marble marble = new Marble();
        marble.display();
        Marble marble1 = new Marble();
        marble1.display();
        Marble marble2 = new Marble();
        marble2.display();
        Marble marble3 = new Marble();
        marble3.display();
        Marble marble4 = new Marble();
        marble4.display();
        Marble marble5 = new Marble();
        marble5.display();
        Marble marble6 = new Marble();
        marble6.display();
        Marble marble7 = new Marble();
        marble7.display();
        Marble marble8 = new Marble();
        marble8.display();
        Marble marble9 = new Marble();
        marble9.display();
        Marble marble10 = new Marble();
        marble10.display();
        Marble marble11 = new Marble();
        marble11.display();
        Marble marble12 = new Marble();
        marble12.display();
        Marble marble13 = new Marble();
        marble13.display();
        Marble marble14 = new Marble();
        marble14.display();
        Marble marble15 = new Marble();
        marble15.display();
        Marble marble16 = new Marble();
        marble16.display();
        Marble marble17 = new Marble();
        marble17.display();
        Marble marble18 = new Marble();
        marble18.display();
        Marble marble19 = new Marble();
        marble19.display();}}