class Satellite {
      static String name;
      static String launchVehicle;
      static String payload;
      static double altitude;
      static String status;
      static String frequencyBand;
      static int lifespan;
      static String fuelType;
      static String manufacturer;
      static boolean solarPowered;
      static boolean communicationEnabled;
      static String groundStation;
      static String launchDate;
      static String missionType;
      static double weight;
      static String orbitType;
      static String operator;
      static boolean isActive;
      static int power;
      static String country;

      public static void main(String[] ar) {
            System.out.println("--------Default Values--------");
            System.out.println("Satellite: " + name + " | Mission: " + missionType + ", Status: " + status);
            System.out.println("Ground Station : " + groundStation);
            System.out.println("Communication Enabled :" + communicationEnabled);
            System.out.println("Solar Power:" + solarPowered);
            System.out.println("Manufacturer :" + manufacturer);
            System.out.println("Fuel Type:" + fuelType);
            System.out.println("Life Span:" + lifespan);
            System.out.println("Frequency Band:" + frequencyBand);
            System.out.println("Altitude :" + altitude);
            System.out.println("Payload :" + payload);
            System.out.println("Launch Vehicle:" + launchVehicle);
            System.out.println("Launch Date:" + launchDate);
            System.out.println("Orbit type :" + orbitType);
            System.out.println("Operator:" + operator);
            System.out.println("Weight:" + weight);
            System.out.println("Power :" + power);
            System.out.println("Country :" + country);
            System.out.println("IS Active:" + isActive);
            System.out.println("--------Actual Values--------");
            name = "INSAT";
            launchVehicle = "Ariane";
            payload = "Sounder";
            altitude = 46000.0;
            status = "working";
            frequencyBand = "S";
            lifespan = 12;
            fuelType = "Chemical";
            manufacturer = "ISRO";
            solarPowered = true;
            communicationEnabled = true;
            groundStation = "Haveri";
            launchDate = "26 July 2013";
            missionType = "Weather Monitoring";
            weight = 2060.0;
            orbitType = "Geostationary";
            operator = "ISRO";
            isActive = true;
            power = 1200;
            country = "India";

            System.out.println("Satellite: " + name + " | Mission: " + missionType + ", Status: " + status);
            System.out.println("Ground Station : " + groundStation);
            System.out.println("Communication Enabled :" + communicationEnabled);
            System.out.println("Solar Power:" + solarPowered);
            System.out.println("Manufacturer :" + manufacturer);
            System.out.println("Fuel Type:" + fuelType);
            System.out.println("Life Span:" + lifespan);
            System.out.println("Frequency Band:" + frequencyBand);
            System.out.println("Altitude :" + altitude);
            System.out.println("Payload :" + payload);
            System.out.println("Launch Vehicle:" + launchVehicle);
            System.out.println("Launch Date:" + launchDate);
            System.out.println("Orbit type :" + orbitType);
            System.out.println("Operator:" + operator);
            System.out.println("Weight:" + weight);
            System.out.println("Power :" + power);
            System.out.println("Country :" + country);
            System.out.println("IS Active:" + isActive);
      }
}
