class ShoppingMall {
  static String name;
  static String location;
  static int shopsCount;
  static boolean hasParking;
  static boolean acAvailable;
  static int floors;
  static int elevators;
  static String openingTime;
  static String closingTime;
  static boolean hasTheatre;
  static boolean foodCourtAvailable;
  static boolean wifiAvailable;
  static boolean kidsPlayArea;
  static int securityGuards;
  static boolean cctvInstalled;
  static String owner;
  static int restrooms;
  static int fireExits;
  static boolean escalatorsAvailable;
  static boolean emergencyClinic;

  public static void main(String[] ar) {
    System.out.println("--------Default Values--------");
    System.out.println("Shopping Mall: " + name + " at " + location);
    System.out.println("Shops: " + shopsCount + ", Floors: " + floors);
    System.out.println(" Has parking:" + hasParking);
    System.out.println("Closing Time" + closingTime);
    System.out.println("Food Court Available" + foodCourtAvailable);
    System.out.println("Elevators " + elevators);
    System.out.println("Security Guard:" + securityGuards);
    System.out.println("WiFi vailability:" + wifiAvailable);
    System.out.println("kids paly area:" + kidsPlayArea);
    System.out.println("cctv installed:" + cctvInstalled);
    System.out.println("owner" + owner);
    System.out.println("rest room :" + restrooms);
    System.out.println("fire exits:" + fireExits);
    System.out.println("Escalators available:" + escalatorsAvailable);
    System.out.println("emergency clinic:" + emergencyClinic);
    System.out.println("AC available:" + acAvailable);
    System.out.println("opening time :" + openingTime);
    System.out.println("has theatre:" + hasTheatre);
    System.out.println("--------Actual Values--------");
    name = "lulu Mall";
    location = "Bangalore";
    shopsCount = 250;
    hasParking = true;
    acAvailable = true;
    floors = 7;
    elevators = 8;
    openingTime = "80:00 AM";
    closingTime = "11:00 PM";
    hasTheatre = true;
    foodCourtAvailable = true;
    wifiAvailable = true;
    kidsPlayArea = true;
    securityGuards = 80;
    cctvInstalled = true;
    owner = "Lulu Group";
    restrooms = 20;
    fireExits = 20;
    escalatorsAvailable = true;
    emergencyClinic = true;

    System.out.println("Shopping Mall: " + name + " at " + location);
    System.out.println("Shops: " + shopsCount + ", Floors: " + floors);
    System.out.println(" Has parking:" + hasParking);
    System.out.println("Closing Time" + closingTime);
    System.out.println("Food Court Available" + foodCourtAvailable);
    System.out.println("Elevators " + elevators);
    System.out.println("Security Guard:" + securityGuards);
    System.out.println("WiFi vailability:" + wifiAvailable);
    System.out.println("kids paly area:" + kidsPlayArea);
    System.out.println("cctv installed:" + cctvInstalled);
    System.out.println("owner" + owner);
    System.out.println("rest room :" + restrooms);
    System.out.println("fire exits:" + fireExits);
    System.out.println("Escalators available:" + escalatorsAvailable);
    System.out.println("emergency clinic:" + emergencyClinic);
    System.out.println("AC available:" + acAvailable);
    System.out.println("opening time :" + openingTime);
    System.out.println("has theatre:" + hasTheatre);
  }
}