class Stadium {
    static String name;
    static String location;
    static int capacity;
    static String surfaceType;
    static boolean hasFloodLights;
    static boolean hasRoof;
    static boolean isIndoor;
    static String primarySport;
    static String establishedYear;
    static String homeTeam;
    static int parkingSlots;
    static boolean vipSeating;
    static boolean mediaBox;
    static boolean scoreboardAvailable;
    static boolean lockerRooms;
    static String managementAuthority;
    static int numberOfEntrances;
    static boolean emergencyExits;
    static boolean foodCourts;
    static boolean publicTransportAccessible;

    public static void main(String[] ar) {
        System.out.println("--------Default Values--------");
        System.out.println("Stadium Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Capacity: " + capacity);
        System.out.println("Surface Type: " + surfaceType);
        System.out.println("Flood Lights: " + hasFloodLights);
        System.out.println("Roof Available: " + hasRoof);
        System.out.println("Indoor Stadium: " + isIndoor);
        System.out.println("Primary Sport: " + primarySport);
        System.out.println("Established Year: " + establishedYear);
        System.out.println("Home Team: " + homeTeam);
        System.out.println("Parking Slots: " + parkingSlots);
        System.out.println("VIP Seating: " + vipSeating);
        System.out.println("Media Box: " + mediaBox);
        System.out.println("Scoreboard: " + scoreboardAvailable);
        System.out.println("Locker Rooms: " + lockerRooms);
        System.out.println("Managed By: " + managementAuthority);
        System.out.println("Entrances: " + numberOfEntrances);
        System.out.println("Emergency Exits: " + emergencyExits);
        System.out.println("Food Courts: " + foodCourts);
        System.out.println("Public Transport Access: " + publicTransportAccessible);
        System.out.println("--------Actual Values--------");

        name = "chinna swami";
        location = "Bglr";
        capacity = 35000;
        surfaceType = "Grass";
        hasFloodLights = true;
        hasRoof = false;
        isIndoor = false;
        primarySport = "Cricket";
        establishedYear = "2000";
        homeTeam = "RCB";
        parkingSlots = 3000;
        vipSeating = true;
        mediaBox = true;
        scoreboardAvailable = true;
        lockerRooms = true;
        managementAuthority = "Bglr";
        numberOfEntrances = 14;
        emergencyExits = true;
        foodCourts = true;
        publicTransportAccessible = true;

        System.out.println("Stadium Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Capacity: " + capacity);
        System.out.println("Surface Type: " + surfaceType);
        System.out.println("Flood Lights: " + hasFloodLights);
        System.out.println("Roof Available: " + hasRoof);
        System.out.println("Indoor Stadium: " + isIndoor);
        System.out.println("Primary Sport: " + primarySport);
        System.out.println("Established Year: " + establishedYear);
        System.out.println("Home Team: " + homeTeam);
        System.out.println("Parking Slots: " + parkingSlots);
        System.out.println("VIP Seating: " + vipSeating);
        System.out.println("Media Box: " + mediaBox);
        System.out.println("Scoreboard: " + scoreboardAvailable);
        System.out.println("Locker Rooms: " + lockerRooms);
        System.out.println("Managed By: " + managementAuthority);
        System.out.println("Entrances: " + numberOfEntrances);
        System.out.println("Emergency Exits: " + emergencyExits);
        System.out.println("Food Courts: " + foodCourts);
        System.out.println("Public Transport Access: " + publicTransportAccessible);
    }
}
