class SwitchBoard {
    static int totalSwitches;
    static int totalSockets;
    static String material;
    static String color;
    static boolean isModular;
    static boolean hasFuse;
    static boolean hasIndicator;
    static int usbPorts;
    static int voltageCapacity;
    static String brand;
    static int length;
    static int width;
    static int height;
    static String installationType;
    static String wiringType;
    static boolean isSmart;
    static String modelNumber;
    static String warranty;
    static boolean overloadProtection;
    static boolean surgeProtection;

    public static void main(String[] ar) {
        System.out.println("--------Default Values--------");
        System.out.println("Switches: " + totalSwitches);
        System.out.println("Sockets: " + totalSockets);
        System.out.println("Material: " + material);
        System.out.println("Color: " + color);
        System.out.println("Modular: " + isModular);
        System.out.println("Fuse: " + hasFuse);
        System.out.println("Indicator: " + hasIndicator);
        System.out.println("USB Ports: " + usbPorts);
        System.out.println("Voltage: " + voltageCapacity);
        System.out.println("Brand: " + brand);
        System.out.println("Size : " + length + "x" + width + "x" + height);
        System.out.println("Installation: " + installationType);
        System.out.println("Wiring: " + wiringType);
        System.out.println("Smart: " + isSmart);
        System.out.println("Model: " + modelNumber);
        System.out.println("Warranty: " + warranty);
        System.out.println("Overload Protection: " + overloadProtection);
        System.out.println("Surge Protection: " + surgeProtection);
        System.out.println("--------Actual Values--------");
        totalSwitches = 10;
        totalSockets = 5;
        material = "Wooden";
        color = "Black";
        isModular = true;
        hasFuse = false;
        hasIndicator = true;
        usbPorts = 1;
        voltageCapacity = 40;
        brand = "own";
        length = 40;
        width = 20;
        height = 10;
        installationType = "door";
        wiringType = "Copper";
        isSmart = false;
        modelNumber = "manu0053";
        warranty = "5 years";
        overloadProtection = true;
        surgeProtection = true;

        System.out.println("Switches: " + totalSwitches);
        System.out.println("Sockets: " + totalSockets);
        System.out.println("Material: " + material);
        System.out.println("Color: " + color);
        System.out.println("Modular: " + isModular);
        System.out.println("Fuse: " + hasFuse);
        System.out.println("Indicator: " + hasIndicator);
        System.out.println("USB Ports: " + usbPorts);
        System.out.println("Voltage: " + voltageCapacity);
        System.out.println("Brand: " + brand);
        System.out.println("Size : " + length + "x" + width + "x" + height);
        System.out.println("Installation: " + installationType);
        System.out.println("Wiring: " + wiringType);
        System.out.println("Smart: " + isSmart);
        System.out.println("Model: " + modelNumber);
        System.out.println("Warranty: " + warranty);
        System.out.println("Overload Protection: " + overloadProtection);
        System.out.println("Surge Protection: " + surgeProtection);
    }
}
