class Theatre {
  static String location;
  static String name;
  static int screens;
  static int totalSeats;
  static boolean onlineBooking;
  static boolean acAvailable;
  static String screenType;
  static boolean is3D;
  static boolean reclinerSeats;
  static int parkingSlots;
  static boolean foodAvailable;
  static boolean surroundSound;
  static String ticketPriceRange;
  static boolean wheelchairAccessible;
  static String openingTime;
  static String closingTime;
  static boolean restroomsAvailable;
  static boolean staffAvailable;
  static boolean securityAvailable;
  static String managerName;

  public static void main(String[] ar) {
    System.out.println("--------Default Values--------");
    System.out.println("Theatre: " + name + ", Location: " + location);
    System.out.println("Screens: " + screens + ", Seats: " + totalSeats);
    System.out.println("managerName" + managerName);
    System.out.println("securityAvailable" + securityAvailable);
    System.out.println("staffAvailable" + staffAvailable);
    System.out.println("surroundSound " + surroundSound);
    System.out.println("ticketPriceRange" + ticketPriceRange);
    System.out.println("restroomsAvailable" + restroomsAvailable);
    System.out.println("closingTime" + closingTime);
    System.out.println("openingTime" + openingTime);
    System.out.println("wheelchairAccessible" + wheelchairAccessible);
    System.out.println("foodAvailable" + foodAvailable);
    System.out.println("parkingSlots" + parkingSlots);
    System.out.println("onlineBooking" + onlineBooking);
    System.out.println("reclinerSeats " + reclinerSeats);
    System.out.println("screenType " + screenType);
    System.out.println("acAvailable" + acAvailable);
    System.out.println("Is 3d" + is3D);
    System.out.println("--------Actual Values--------");
    name = "PVR Cinemas";
    location = "Mumbai";
    screens = 8;
    totalSeats = 1200;
    onlineBooking = true;
    acAvailable = true;
    screenType = "IMAX";
    is3D = true;
    reclinerSeats = true;
    parkingSlots = 200;
    foodAvailable = true;
    surroundSound = true;
    ticketPriceRange = "₹200-₹500";
    wheelchairAccessible = true;
    openingTime = "9:00 AM";
    closingTime = "12:00 AM";
    restroomsAvailable = true;
    staffAvailable = true;
    securityAvailable = true;
    managerName = "Rajesh Menon";

    System.out.println("Theatre: " + name + ", Location: " + location);
    System.out.println("Screens: " + screens + ", Seats: " + totalSeats);
    System.out.println("managerName" + managerName);
    System.out.println("securityAvailable" + securityAvailable);
    System.out.println("staffAvailable" + staffAvailable);
    System.out.println("surroundSound " + surroundSound);
    System.out.println("ticketPriceRange" + ticketPriceRange);
    System.out.println("restroomsAvailable" + restroomsAvailable);
    System.out.println("closingTime" + closingTime);
    System.out.println("openingTime" + openingTime);
    System.out.println("wheelchairAccessible" + wheelchairAccessible);
    System.out.println("foodAvailable" + foodAvailable);
    System.out.println("parkingSlots" + parkingSlots);
    System.out.println("onlineBooking" + onlineBooking);
    System.out.println("reclinerSeats " + reclinerSeats);
    System.out.println("screenType " + screenType);
    System.out.println("acAvailable" + acAvailable);
    System.out.println("Is 3d" + is3D);
  }
}
